---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: fluentd-logging
    kubernetes.io/cluster-service: "true"
    pod-template-generation: "1"
    version: v1
  name: fluentd
  namespace: kube-system
spec:
  ports:
  - port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    k8s-app: fluentd-logging
    kubernetes.io/cluster-service: "true"
    pod-template-generation: "1"
    version: v1
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-opensearch
#        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
#      - name: fluentd
#        image: fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.7
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxq.opensearch.us-ashburn-1.oci.oraclecloud.com"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "https"
          # =====================
          # Option to configure elasticsearch plugin with self signed certs
          # ================================================================
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "true"
          # Option to configure elasticsearch plugin with tls
          # ================================================================
          - name: FLUENT_ELASTICSEARCH_SSL_VERSION
            value: "TLSv1_2"
          # X-Pack Authentication
          # =====================
          - name: FLUENT_ELASTICSEARCH_USER
            value: "crixxxxxxx.xxxxxxxxxxxa@oracle.com"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "xxxxxxxxxxxxxxxxxxxxxxx"
          # =====================
          #- name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
          #  value: /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          # =====================
          #- name: FLUENT_CONF
          #  value: fluent.conf
          #- name: FLUENTD_ARGS
          #  value: -c /fluentd/etc/fluent.conf
          # =====================
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name:  fdconf
          mountPath:  /fluentd/etc/
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fdconf
        configMap:
          name: fluentdconf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: kube-system
data:
  fluent.conf: |
      <source>
        @type forward
        port 24224
      </source>

      <match **.*>
        @type opensearch
        host axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxq.opensearch.us-ashburn-1.oci.oraclecloud.com
        port 9200
        scheme https
        ssl_version TLSv1_2
        user crixxxxxxxxx.xxxxxxxxxxxx@oracle.com
        password xxxxxxxxxxxxxxxxxxxxxx
        flush_interval 1s
        logstash_prefix fluentd
        logstash_format true
        include_timestamp true
        include_tag_key true
        retry_limit 1
      </match>

      <match>
        @type stdout
      </match>
---
